src/accounts/urls.py
from django.urls import path

from .views import (LogoutPageView, AgentDetailView,
                    RegisterView, LoginPageView, send_login_email, activate_login_email,
                    UserActivationSentView)

app_name = 'accounts'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginPageView.as_view(), name='login'),
    path('send_email/', send_login_email, name='send_login_email'),
    path('activate_email/<uuid:uid>/', activate_login_email, name='activate'),
    path('logout/', LogoutPageView.as_view(), name='logout'),
    path('agents/<slug:slug>/', AgentDetailView.as_view(), name='profile'),
    path('user_activation_sent/', UserActivationSentView.as_view(),
         name='user_activation_sent')
]

src/fubanna/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

from main.views import home_files

urlpatterns = [
    re_path(r'^(?P<filename>(robots.txt)|(humans.txt))$',
            home_files, name='home-files'),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('admin/statuscheck/', include('celerybeat_status.urls')),
    path('', include('main.urls', namespace='main')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
)

if settings.DEBUG:
    urlpatterns = urlpatterns + \
        static(settings.STATIC_ROOT, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/main/urls.py
from django.urls import path

from .views import (HomePageView, ContactPageView)

app_name = 'main'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('contact/', ContactPageView.as_view(), name='contact'),
]

src/templates/base/css.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/reality-icon.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/bootsnav.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/jquery.fancybox.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/owl.carousel.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/owl.transitions.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/cubeportfolio.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/settings.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/range-Slider.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/search.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">

src/templates/base/footer.html
<!--Footer-->
<footer class="footer_third">
    <div class="container contacts">
        <div class="row">
            <div class="col-sm-4 text-center">
                <div class="info-box first">
                    <div class="icons"><i class="icon-telephone114"></i></div>
                    <ul class="text-center">
                        <li><strong>Phone Number</strong></li>
                        <li>+1 900 234 567 - 68</li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-4 text-center">
                <div class="info-box">
                    <div class="icons"><i class="icon-icons74"></i></div>
                    <ul class="text-center">
                        <li><strong>Manhattan Hall,</strong></li>
                        <li>Castle Melbourne, australia</li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-4 text-center">
                <div class="info-box">
                    <div class="icons"><i class="icon-icons142"></i></div>
                    <ul class="text-center">
                        <li><strong>Email Address</strong></li>
                        <li><a href="#.">info@castle.com</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="container padding_top">
        <div class="row">
            <div class="col-md-3 col-sm-6">
                <div class="footer_panel bottom30">
                    <a href="#." class="logo bottom30"><img src="images/logo-white.png" alt="logo"></a>
                    <p class="bottom15">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh
                        tempor cum consectetuer
                        adipiscing.
                    </p>
                    <p class="bottom15">If you are interested in castle do not wait and <a href="#.">BUY IT NOW!</a></p>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="footer_panel bottom30">
                    <h4 class="bottom30 heading">Search by Area</h4>
                    <table style="width:100%;">
                        <tbody>
                            <tr>
                                <td>
                                    <ul class="links">
                                        <li><a href="#."><i></i>About</a></li>
                                        <li class="active"><a href="#."><i></i>News</a></li>
                                        <li><a href="#."> <i></i>Contacts</a></li>
                                        <li><a href="#."><i></i>Testimonials</a></li>
                                        <li><a href="#."><i></i>Typography</a></li>
                                    </ul>
                                </td>
                                <td class="text-right">
                                    <ul class="links text-left">
                                        <li><a href="#."><i></i>Services</a></li>
                                        <li class="active"><a href="#."><i></i>Careers</a></li>
                                        <li><a href="#."><i></i>Our team</a></li>
                                        <li><a href="#."><i></i>Shop</a></li>
                                        <li><a href="#."><i></i>Our approach</a></li>
                                    </ul>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="footer_panel bottom30">
                    <h4 class="bottom30 heading">Latest News</h4>
                    <div class="media bottom30">
                        <div class="media-body">
                            <a href="#.">Nearest mall in high tech Goes google map your villa</a>
                            <span id="local-date"><i class="icon-clock5"></i>{{ today }}</span>
                        </div>
                    </div>
                    <div class="media">
                        <div class="media-body">
                            <a href="#.">Nearest mall in high tech Goes google map your villa</a>
                            <span><i class="icon-clock5"></i>Feb 22, 2017</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="footer_panel bottom30">
                    <h4 class="bottom30 heading">Subscribe</h4>
                    <p>Sign up with your email to get latest updates and offers</p>
                    <form class="top30" action="{% url 'accounts:login' %}" method="POST">
                        {% csrf_token %}
                        <input class="search" placeholder="Enter your Email" type="search" name="email">
                        <a class="button_s" href="#">
                            <i class="icon-mail-envelope-open"></i>
                        </a>
                    </form>
                </div>
            </div>
        </div>
        <!--CopyRight-->
        <div class="copyright_simple">
            <div class="row">
                <div class="col-md-6 col-sm-5 top20 bottom20">
                    <p>Copyright &copy; 2017 <span>Castle</span>. All rights reserved.</p>
                </div>
                <div class="col-md-6 col-sm-7 text-right top15 bottom10">
                    <ul class="social_share">
                        <li><a href="#." class="facebook"><i class="icon-facebook-1"></i></a></li>
                        <li><a href="#." class="twitter"><i class="icon-twitter-1"></i></a></li>
                        <li><a href="#." class="google"><i class="icon-google4"></i></a></li>
                        <li><a href="#." class="linkden"><i class="fa fa-linkedin"></i></a></li>
                        <li><a href="#." class="vimo"><i class="icon-vimeo3"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>

src/templates/base/js.html
{% load static %}

<script src="{% static 'js/jquery-2.1.4.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.appear.js' %}"></script>
<script src="{% static 'js/jquery-countTo.js' %}"></script>
<script src="{% static 'js/bootsnav.js' %}"></script>
<script src="{% static 'js/masonry.pkgd.min.js' %}"></script>
<script src="{% static 'js/jquery.parallax-1.1.3.js' %}"></script>
<script src="{% static 'js/jquery.cubeportfolio.min.js' %}"></script>
<script src="{% static 'js/range-Slider.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/selectbox-0.2.min.js' %}"></script>
<script src="{% static 'js/zelect.js' %}"></script>
<script src="{% static 'js/jquery.fancybox.js' %}"></script>
<script src="{% static 'js/jquery.themepunch.tools.min.js' %}"></script>
<script src="{% static 'js/jquery.themepunch.revolution.min.js' %}"></script>
<script src="{% static 'js/revolution.extension.actions.min.js' %}"></script>
<script src="{% static 'js/revolution.extension.layeranimation.min.js' %}"></script>
<script src="{% static 'js/revolution.extension.navigation.min.js' %}"></script>
<script src="{% static 'js/revolution.extension.parallax.min.js' %}"></script>
<script src="{% static 'js/revolution.extension.slideanims.min.js' %}"></script>
<script src="{% static 'js/revolution.extension.video.min.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>
<script src="{% static 'js/functions.js' %}"></script>

src/templates/base/loader.html
<!--Loader-->
<div class="loader">
    <div class="span">
        <div class="location_indicator"></div>
    </div>
</div>
<!--Loader-->