src/accounts/urls.py
from django.urls import path

from .views import (LogoutPageView, AgentDetailView,
                    RegisterView, LoginPageView, send_login_email, activate_login_email,
                    UserActivationSentView)

app_name = 'accounts'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginPageView.as_view(), name='login'),
    path('send_email/', send_login_email, name='send_login_email'),
    path('activate_email/<uuid:uid>/', activate_login_email, name='activate'),
    path('logout/', LogoutPageView.as_view(), name='logout'),
    path('agents/<slug:slug>/', AgentDetailView.as_view(), name='profile'),
    path('user_activation_sent/', UserActivationSentView.as_view(),
         name='user_activation_sent')
]

src/fubanna/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

from main.views import home_files

urlpatterns = [
    re_path(r'^(?P<filename>(robots.txt)|(humans.txt))$',
            home_files, name='home-files'),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('admin/statuscheck/', include('celerybeat_status.urls')),
    path('', include('main.urls', namespace='main')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
)

if settings.DEBUG:
    urlpatterns = urlpatterns + \
        static(settings.STATIC_ROOT, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/main/urls.py
from django.urls import path

from .views import (HomePageView, ContactPageView)

app_name = 'main'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('contact/', ContactPageView.as_view(), name='contact'),
]

src/accounts/models.py
import uuid
import random
import os

from django.db import models
from django.db.models.signals import pre_save
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin
from django.shortcuts import reverse

from .utils import unique_slug_generator


def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)

    return name, ext


def upload_image_path(instance, filename):
    new_filename = random.randint(1, 2343456545654)
    name, ext = get_filename_ext(filename)
    print(get_filename_ext(filename))
    final_filename = f'{new_filename}{ext}'

    return f'agents/{new_filename}/{final_filename}'


class UserManager(BaseUserManager):
    # pass
    def create_user(self, email, password=None):

        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        user = self.create_user(
            email,
            password=password,
        )
        user.is_admin = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):

    email = models.EmailField(_('email'), primary_key=True)
    is_agent = models.BooleanField(_('agent'), default=False)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    REQUIRED_FIELDS = []
    USERNAME_FIELD = 'email'
    is_anonymous = False
    is_authenticated = True

    class Meta:
        verbose_name = _('user')

    objects = UserManager()

    def __str__(self):
        return self.email

    @property
    def is_staff(self):
        return self.is_admin


class Token(models.Model):
    email = models.EmailField()
    uid = models.UUIDField(max_length=40, default=uuid.uuid4)


class Agent(models.Model):
    email = models.EmailField(unique=True)
    phone_number = models.CharField(max_length=15)
    screen_name = models.CharField(max_length=100)
    slug = models.SlugField(blank=True, max_length=20,
                            db_index=True, unique=True)
    image = models.ImageField(
        upload_to=upload_image_path, blank=True, null=True)

    def __str__(self):
        return self.screen_name

    def get_absolute_url(self):
        return reverse('accounts:profile', args=[str(self.slug)])


# from main.tasks import send_verification_email


# def user_post_save(sender, instance, signal, *args, **kwargs):
#     if not instance.is_verified:
#         send_verification_email.delay(instance.pk)
#         print('sent')


# signals.post_save.connect(user_post_save, User)


def agent_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


pre_save.connect(agent_pre_save_receiver, sender=Agent)

src/accounts/forms.py
import uuid

from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import get_user_model
from django.template.loader import render_to_string
from django.core.mail import EmailMessage

from .models import Agent, Token
from .tasks import send_register_email_task

User = get_user_model()


class LoginForm(AuthenticationForm):
    email = forms.EmailField(widget=forms.EmailInput(
        attrs={'placeholder': 'Your Email', 'class': 'keyword-input', 'id': 'login_email'}))

    def send_email(self):
        # later put it in task
        # send_login_email.delay(self.cleaned_data)

        email = self.cleaned_data.get('email')
        token = Token.objects.get(email=email)
        current_site = 'localhost:8000'
        mail_subject = 'Activate your Fubanna account.'
        message = render_to_string('accounts/login_activation_email.html', {
            'domain': current_site,
            'uid': token.uid
        })
        email = EmailMessage(
            mail_subject, message, to=[email]
        )
        email.send()


class RegisterForm(forms.ModelForm):
    email = forms.EmailField(widget=forms.EmailInput(
        attrs={'placeholder': 'Your Email', 'class': 'keyword-input', 'id': 'register_email'}))
    phone_number = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': 'Your Phone Number', 'class': 'keyword-input', 'id': 'phone_number'}))
    screen_name = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Your Name', 'class': 'keyword-input', 'id': 'screen_name'}))

    class Meta:
        model = Agent
        fields = ['email', 'phone_number', 'screen_name', 'slug']

    def send_email(self):
        send_register_email_task.delay(self.cleaned_data)

src/accounts/views.py
import uuid
import sys

from django.shortcuts import render, HttpResponseRedirect
from django.views.generic import CreateView, ListView, DetailView, TemplateView
from django.urls import reverse_lazy, reverse
from django.contrib.auth import get_user_model, login as auth_login, authenticate

from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages

from accounts.forms import LoginForm, RegisterForm
from accounts.tasks import send_login_email_task

User = get_user_model()


def send_login_email(request):
    email = request.POST['email']
    send_login_email_task.delay(email)

    messages.success(
        request, "Check your email, we've sent you a link you can use to log in.")

    return HttpResponseRedirect(reverse('accounts:login'))


def activate_login_email(request, uid):
    print('uid:', uid)
    user = authenticate(uid)

    if request.user.is_authenticated:
        print('authenticated')

    if user is not None:
        print('login')
        auth_login(request, user)

    return HttpResponseRedirect(reverse('main:home'))

# def agent_activation_view(request, uidb64, token):
#     try:
#         uid = force_text(urlsafe_base64_decode(uidb64))
#         user = User.objects.get(verification_uuid=uid)
#     except (TypeError, ValueError, OverflowError, User.DoesNotExist):
#         user = None

#     if user is not None and account_activation_token.check_token(user, token):
#         user.is_active = True
#         user.is_verified = True
#         user.save()
#         login(request, user)
#         return redirect('main:home')

#     return render(request, 'main/user_activation_invalid.html')


class AgentUserListView(ListView):
    template_name = 'accounts/user_list.html'
    queryset = User.objects.all()
    context_object_name = 'users'


class AgentUserDetailView(DetailView):
    model = User
    template_name = 'main/users/user_detail.html'


class UserActivationSentView(TemplateView):
    template_name = 'main/user_activation_sent.html'


class LoginPageView(LoginView):

    template_name = 'accounts/login.html'
    form_class = LoginForm
    success_url = reverse_lazy('main:home')

    def get_context_data(self, **kwargs):
        context = super(LoginPageView, self).get_context_data(**kwargs)
        print(context)
        return context


class LogoutPageView(LogoutView, LoginRequiredMixin):
    login_url = reverse_lazy('main:home')


class RegisterView(CreateView):

    form_class = RegisterForm
    template_name = 'auth/register.html'
    success_url = reverse_lazy('main:user_activation_sent')

    def get_context_data(self, **kwargs):
        context = super(RegisterView, self).get_context_data(**kwargs)
        context['title'] = 'Register Page'
        print(context)

        return context

src/accounts/templates/accounts/agent_list.html
{% extends '../../base.html' %}

{% block content1 %}
<p>User List</p>
{% endblock %}

src/accounts/templates/accounts/agent_verification_email.html
{% autoescape off %}
Hi {{ screen_name }},

Please follow up on this agent {{ screen_name }},

Details are as follow:

Email: {{ email }}
Phone Number: {{ phone_number }}

{% endautoescape %}

src/accounts/templates/accounts/agent_verification_invalid.html
{% extends '../base.html' %}

{% block content %}
<p>The confirmation link was invalid, possibly because it has already been used.</p>
{% endblock %}

src/accounts/templates/accounts/agent_verification_sent.html
{% extends '../base.html' %}

{% block content %}
<p>Please confirm your email address to complete the registration. </p>
{% endblock %}

src/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
{% include 'base/header.html' %}

<!-- Page Banner Start-->
<section class="page-banner padding">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <h1 class="text-uppercase">Login</h1>
                <p>Serving you since 1999. Lorem ipsum dolor sit amet consectetur adipiscing elit.</p>
                <ol class="breadcrumb text-center">
                    <li><a href="#">Home</a></li>
                    <li><a href="#">Properties</a></li>
                    <li class="active">Login</li>
                </ol>
            </div>
        </div>
    </div>
</section>
<!-- Page Banner End -->


<!-- Login -->
<section id="login" class="padding">
    <div class="container">
        <h3 class="hidden">hidden</h3>
        <div class="row">
            <div class="col-md-12 text-center">
                <div class="profile-login">
                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs" role="tablist">
                        <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab"
                                data-toggle="tab">Login</a></li>
                        <li role="presentation"><a href="#profile" aria-controls="profile" role="tab"
                                data-toggle="tab">Become an Agent</a></li>
                    </ul>
                    <!-- Tab panes -->
                    <div class="tab-content padding_half">
                        <div role="tabpanel" class="tab-pane fade in active" id="home">
                            <div class="agent-p-form">
                                <form action="{% url 'accounts:send_login_email' %}" method="POST"
                                    class="callus clearfix">
                                    {% csrf_token %}

                                    <div class="single-query form-group  col-sm-12">
                                        {{ login_form.email }}
                                    </div>
                                    <div class="row">
                                        <div class="col-sm-12">
                                            <div class="col-sm-6">
                                                <div class="search-form-group white form-group text-left">
                                                    <div class="check-box-2"><i><input type="checkbox"
                                                                name="check-box"></i></div>
                                                    <span>Remember Me</span>
                                                </div>
                                            </div>
                                            <div class="col-sm-6 text-right">
                                                <a href="#" class="lost-pass">Lost your password?</a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class=" col-sm-12">
                                        <input type="submit" value="Send" class="btn-slide border_radius">
                                    </div>
                                    <div class="or-seperator"><i>or</i></div>
                                    <p class="text-center" style="color: white">Login with your social media account</p>
                                    <div class="text-center social-btn">
                                        <a href="#" class="btn btn-primary"><i class="fa fa-facebook"></i>&nbsp;
                                            Facebook</a>
                                        <a href="#" class="btn btn-info"><i class="fa fa-twitter"></i>&nbsp; Twitter</a>
                                        <a href="#" class="btn btn-danger"><i class="fa fa-google"></i>&nbsp; Google</a>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <div role="tabpanel" class="tab-pane fade" id="profile">
                            <div class="agent-p-form">
                                <form method="POST" action="{% url 'accounts:register' %}" class="callus clearfix">

                                    {% csrf_token %}

                                    <div class="single-query col-sm-12 form-group">
                                        {{ register_form.email }}
                                    </div>
                                    <div class="single-query col-sm-12 form-group">
                                        {{ register_form.phone_number }}
                                    </div>
                                    <div class="single-query col-sm-12 form-group">
                                        {{ register_form.screen_name }}
                                    </div>
                                    <div class="search-form-group white col-sm-12 form-group text-left">
                                        <div class="check-box-2"><i><input type="checkbox" name="check-box"></i></div>
                                        <span>Receive Newsletter</span>
                                    </div>
                                    <div class="col-md-12 col-sm-12 col-xs-12 text-center">
                                        <div class="query-submit-button">
                                            <input type="submit" value="Register" class="btn-slide">
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Login end -->

{% endblock %}

src/accounts/templates/accounts/login_activation_email.html
{% autoescape off %}
Hello,

Your login link for Fubanna, Use this link to log in:

http://{{ domain }}{% url 'accounts:activate' uid=uid %}
{% endautoescape %}

src/accounts/templates/accounts/login_activation_invalid.html
{% extends '../base.html' %}

{% block content %}
<p>The confirmation link was invalid, possibly because it has already been used.</p>
{% endblock %}

src/accounts/templates/accounts/login_activation_sent.html
{% extends '../base.html' %}

{% block content %}
<h1>Email sent</h1>
<p>Check your email, you'all find a message with a link that will log you into the site. </p>
{% endblock %}

src/accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% block content %}
{% include 'base/header.html' %}


<!-- Page Banner Start-->
<section class="page-banner padding">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1 class="text-uppercase">Profile</h1>
        <p>Serving you since 1999. Lorem ipsum dolor sit amet consectetur adipiscing elit.</p>
        <ol class="breadcrumb text-center">
          <li><a href="#">Home</a></li>
          <li><a href="#">Pages</a></li>
          <li class="active">Profile</li>
        </ol>
      </div>
    </div>
  </div>
</section>
<!-- Page Banner End -->




<!-- Profile Start -->
<section id="agent-2-peperty" class="profile padding">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <ul class="f-p-links margin_bottom">
          <li><a href="profile.html" class="active"><i class="icon-icons230"></i>Profile</a></li>
          <li><a href="my_properties.html"><i class="icon-icons215"></i> My Properties</a></li>
          <li><a href="submit_property.html"><i class="icon-icons215"></i> Submit Property</a></li>
          <li><a href="favorite_properties.html"><i class="icon-icons43"></i> Favorite Properties</a></li>
          <li><a href="login.html"><i class="icon-lock-open3"></i>Logout</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="container-3">
    <div class="row">
      <div class="col-md-4 col-sm-6 col-xs-12">
        <h2 class="text-uppercase bottom30">my profile</h2>
        <div class="agent-p-img">
          <img src="images/profile.jpg" class="img-responsive" alt="image" />
          <a href="#" class="top10 bottom20">Update Profile Picture</a>
          <p class="text-center">Minimum 215px x 215px<span>*</span></p>
        </div>
      </div>
      <div class="col-md-8">
        <div class="profile-form">
          <div class="row">
            <form class="callus">
              <div class="col-sm-4">
                <div class="single-query">
                  <label>Your Name:</label>
                </div>
              </div>
              <div class="col-sm-8">
                <div class="single-query form-group">
                  {{ form.screen_name }}
                </div>
              </div>
              <div class="col-sm-4">
                <div class="single-query">
                  <label>Phone:</label>
                </div>
              </div>
              <div class="col-sm-8">
                <div class="single-query form-group">
                  <input type="text" placeholder="(+01) 34 56 7890" class="keyword-input">
                </div>
              </div>
              <div class="col-sm-4">
                <div class="single-query">
                  <label>Mobile:</label>
                </div>
              </div>
              <div class="col-sm-8">
                <div class="single-query form-group">
                  <input type="text" placeholder="(+033) 34 56 7890" class="keyword-input">
                </div>
              </div>
              <div class="col-sm-4">
                <div class="single-query">
                  <label>Email Adress:</label>
                </div>
              </div>
              <div class="col-sm-8">
                <div class="single-query form-group">
                  <input type="text" placeholder="bohdan@realtyhomes.com" class="keyword-input">
                </div>
              </div>
              <div class="col-sm-4">
                <div class="single-query">
                  <label>Skype:</label>
                </div>
              </div>
              <div class="col-sm-8">
                <div class="single-query form-group">
                  <input type="text" placeholder="bohdan.kononets" class="keyword-input">
                </div>
              </div>
              <div class="col-sm-4">
                <div class="single-query">
                  <label>About:</label>
                </div>
              </div>
              <div class="col-sm-8">
                <div class="single-query form-group">
                  <textarea placeholder="Write here somthing about yours" class="form-control"></textarea>
                </div>
              </div>
              <div class="col-md-12 col-sm-12 col-xs-12 text-right">
                <a class="btn-blue border_radius" href="#.">Save Changes</a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-md-5 col-sm-6 col-xs-12 profile-form margin40">
        <h3 class="bottom30 margin40">My Social Network</h3>
        <div class="row">
          <form class="callus">
            <div class="col-sm-4">
              <div class="single-query">
                <label>Facebook:</label>
              </div>
            </div>
            <div class="col-sm-8">
              <div class="single-query form-group">
                <input type="text" placeholder="http://facebook.com" class="keyword-input">
              </div>
            </div>
            <div class="col-sm-4">
              <div class="single-query">
                <label>Twitter:</label>
              </div>
            </div>
            <div class="col-sm-8">
              <div class="single-query form-group">
                <input type="text" placeholder="http://twitter.com" class="keyword-input">
              </div>
            </div>
            <div class="col-sm-4">
              <div class="single-query">
                <label>Google Plus:</label>
              </div>
            </div>
            <div class="col-sm-8">
              <div class="single-query form-group">
                <input type="text" placeholder="http://google-plus.com" class="keyword-input">
              </div>
            </div>
            <div class="col-sm-4">
              <div class="single-query">
                <label>Linkedin:</label>
              </div>
            </div>
            <div class="col-sm-8">
              <div class="single-query form-group">
                <input type="text" placeholder="http://linkedin.com" class="keyword-input">
              </div>
            </div>
            <div class="col-md-12 col-sm-12 col-xs-12 text-right">
              <a class="btn-blue border_radius" href="#.">Save Changes</a>
            </div>
          </form>
        </div>
      </div>
      <div class="col-md-2 hidden-xs"></div>
    </div>
  </div>
</section>
<!-- Profile end -->


{% endblock %}